nativ1/fakture/urls.py
from django.urls import path
from . import views

app_name = 'fakture'

urlpatterns = [
    path('', views.pocetna_stranica, name='index'),
    path('pdf/<str:pk>/', views.pdf_generator, name='pdf1'),
    path('kreiranje-fakture/', views.KreirajFakturu.as_view(), name='kreiraj-fakturu'),
    path('kreiranje-fakture/<int:pk>/prodaja/', views.KreirajFakturuProdaja.as_view(), name='faktura-prodaja'),
    path('kreiranje-fakture/prodaja/<int:pk>/', views.faktura_skica_gotova, name='faktura-skica'),
    path('kreiranje-fakture/prodaja/<int:pk>/detalji/', views.ProdajaDetalji.as_view(), name='prodaja-detalji'),
    path('kreiranje-fakture/prodaja/<int:pk>/izmjena/', views.ProdajaIzmjena.as_view(), name='prodaja-izmjena'),
    path('kreiranje-fakture/prodaja/<int:pk>/brisanje/', views.ProdajaBrisanje.as_view(), name='prodaja-brisanje'),
    path('kreiranje-fakture/<int:pk>/izmjena/', views.FakturaUpdate.as_view(), name='faktura-izmjena'),
    path('kreiranje-fakture/izmjena/<int:pk>/prodaja/', views.ProdajaGlavnaUpdate.as_view(), name='faktura-prodaja-izmjena'),
    path('lista_faktura/', views.FaktureLista.as_view(), name='lista_fakturi'),
    path('kupci/', views.KupciLista.as_view(), name='lista-kupci'),
    path('kupci/novi-kupac/', views.KupacNovi.as_view(), name='kupac-novi'),
    path('kupac/<int:pk>/', views.KupacDetalji.as_view(), name='kupac-detalji'),
    path('kupac/<int:pk>/update/', views.KupacUpdate.as_view(), name='kupac-update'),
    path('base-nativ/', views.base, name='base-nativ'),
    path('valute/', views.KreirajValute.as_view(), name='kreiraj-valutu'),
    path('<int:pk>/', views.ValuteUpdate.as_view(), name='valute_update'),
    path('usluge-lista/', views.UslugeList.as_view(), name='usluge-lista'),
    path('usluge-lista/kreiraj-uslugu/', views.UslugaKreiraj.as_view(), name='usluge-kreiraj'),
    path('usluge-lista/kreiraj-uslugu/<int:pk>/update/', views.UslugaUpdate.as_view(), name='usluge-update'),
    path('pozicija/kreiraj/', views.PozicijaKreiraj.as_view(), name='pozicije-kreiraj'),
    path('pozicija/kreiraj/<int:pk>/update/', views.PozicijaUpdate.as_view(), name='pozicija-update'),
    path('lista_faktura/<str:year>/', views.faktura_po_godinama, name='fakture_po_godinama'),
    path('lista_ponuda/', views.PonudaLista.as_view(), name='ponuda-lista'),
    path('ponuda-create/', views.KreirajPonudu.as_view(), name='ponuda-create'),
    path('ponuda-create/<int:pk>/ponuda-prodaja/', views.KreirajPonuduProdaja.as_view(), name='ponuda-prodaja'),
    path('ponuda-create/ponuda-prodaja/<int:pk>/detalji/', views.ProdajaPonudaDetalji.as_view(), name='ponuda-prodaja-detalji'),
    path('ponuda-create/prodaja-ponuda/<int:pk>/', views.ponuda_skica_gotova, name='ponuda-skica'),
    path('ponuda-pdf/<str:pk>/', views.pdf_generator_ponuda, name='ponuda-pdf'),
    path('ponuda-create/<int:pk>/izmjena/', views.PonudaUpdate.as_view(), name='ponuda-izmjena'),
    path('ponuda-create/prodaja/<int:pk>/brisanje/', views.PonudaProdajaBrisanje.as_view(), name='ponuda-prodaja-brisanje'),
    path('ponuda-create/prodaja/<int:pk>/izmjena/', views.PonudaProdajaIzmjena.as_view(), name='ponuda-prodaja-izmjena'),
    path('usluge-lista/<str:year>/', views.ponude_po_godinama, name='ponude_po_godinama'),
]

nativ1/nativ1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('fakture/', include('fakture.urls')),
    path('', RedirectView.as_view(url='fakture/')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

nativ1/fakture/forms.py
from django.forms import ModelForm
from django import forms
from django.db.models.functions import Concat
from .models import Faktura, Prodaja, Ponuda, ProdajaPonuda
from django.contrib.admin import widgets
from django.core.exceptions import ValidationError


class FakturaForma(ModelForm):
    class Meta:
        model = Faktura
        fields = '__all__'
        exclude = ('drzava','rok_placanja', 'valuta', 'racun', 'racun_njemacki', 'nacin_placanja')
        widgets = {
            'datum_fakture': forms.DateInput(format=('%d/%m/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
        }

    def clean(self):
        broj_f = self.cleaned_data['broj_fakture']
        datum_f = self.cleaned_data['datum_fakture']
        datum = Faktura.objects.filter(broj_fakture=broj_f, datum_fakture__year=datum_f.year)
        if datum:
            raise ValidationError('Ne možete unjeti isti broj fakture u tekućoj godini!')

class FakturaUpdateForm(ModelForm):

    class Meta:
        model = Faktura
        exclude = ('drzava','rok_placanja', 'valuta', 'racun', 'racun_njemacki', 'nacin_placanja')

class ProdajaForma(ModelForm):

    class Meta:
        model = Prodaja
        fields = '__all__'
        exclude = ('neto_cijena_proizvoda', 'pdv', 'bruto_cijena_proizvoda', 'neto_cijena', 'bruto_cijena')

    def clean(self):
        faktura_id = self.cleaned_data['faktura']
        poz_np = self.cleaned_data['pozicija']
        opi_usl = self.cleaned_data['opis_usluge']

        usluga = Prodaja.objects.filter(faktura_id=faktura_id.pk, pozicija__naziv_pozicije=poz_np.naziv_pozicije,
                                        pozicija__pos_NSN=poz_np.pos_NSN, pozicija__pos_broj=poz_np.pos_broj,
                                        opis_usluge=opi_usl.pk)

        if usluga:
            raise ValidationError('Pokušavate unjeti već postojeće elemente!')

class PonudaForma(ModelForm):
    class Meta:
        model = Ponuda
        fields = '__all__'
        exclude = ('drzava','rok_placanja', 'valuta', 'racun', 'racun_njemacki', 'nacin_placanja')
        widgets = {
            'datum_ponude': forms.DateInput(format=('%d/%m/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
        }

    def clean(self):
        broj_p = self.cleaned_data['broj_ponude']
        datum_p = self.cleaned_data['datum_ponude']
        datum = Ponuda.objects.filter(broj_ponude=broj_p, datum_ponude__year=datum_p.year)
        if datum:
            raise ValidationError('Ne možete unjeti isti broj ponude u tekućoj godini!')

class PonudaProdajaForma(ModelForm):

    class Meta:
        model = ProdajaPonuda
        fields = '__all__'
        exclude = ('neto_cijena_proizvoda', 'pdv', 'bruto_cijena_proizvoda', 'neto_cijena', 'bruto_cijena')

    def clean(self):
        ponuda_id = self.cleaned_data['ponuda']
        poz_np = self.cleaned_data['pozicija']
        opi_usl = self.cleaned_data['opis_usluge']

        usluga = ProdajaPonuda.objects.filter(ponuda_id=ponuda_id.pk, pozicija__naziv_pozicije=poz_np.naziv_pozicije,
                                        pozicija__pos_NSN=poz_np.pos_NSN, pozicija__pos_broj=poz_np.pos_broj,
                                        opis_usluge=opi_usl.pk)

        if usluga:
            raise ValidationError('Pokušavate unjeti već postojeće elemente!')

nativ1/fakture/views.py
from django.shortcuts import render

# Create your views here.
import os
from django.conf import settings
import decimal
from weasyprint import HTML, CSS
from django.shortcuts import render
from django.views.generic import View, ListView, UpdateView, DetailView, CreateView, DeleteView
from django.db.models import Sum
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from .models import Korisnik, Kupac, Usluga, Faktura, Prodaja, Pozicija, Valute, Ponuda, ProdajaPonuda
from django.template.loader import get_template, render_to_string
from django.http import HttpResponse
from django.urls import reverse_lazy, reverse
from .forms import FakturaForma, ProdajaForma, PonudaForma, PonudaProdajaForma, FakturaUpdateForm
from django.db.models.functions import ExtractYear, TruncYear, Cast
from django.db.models.fields import DateField


def pdf_generator(request, pk):
    faktura = Faktura.objects.get(id=pk)
    prodaja = Prodaja.objects.filter(faktura__id=pk)
    prodaja_do_8 = Prodaja.objects.filter(faktura__id=pk)[:8]
    prodaja_8 = Prodaja.objects.filter(faktura__id=pk)[8:]
    prodaja_do_16 = Prodaja.objects.filter(faktura__id=pk)[8:24]
    prodaja_16 = Prodaja.objects.filter(faktura__id=pk)[24:]
    neto_suma = Prodaja.objects.filter(faktura__id=pk).aggregate(net_suma=Sum('neto_cijena'))
    bruto_suma = Prodaja.objects.filter(faktura__id=pk).aggregate(brt_suma=Sum('bruto_cijena'))
    formatirano1= round(neto_suma['net_suma'], 2)
    formatirano = round(bruto_suma['brt_suma'], 2)
    bruto_suma['brt_suma'] = formatirano
    neto_suma['net_suma'] = formatirano1
    prodaja_count = len(prodaja)
    korisnik = Korisnik.objects.get(username=request.user.username)
    valuta = Valute.objects.get(valute='EUR')
    avans = faktura.avansno_uplaceno
    bruto_suma_avans = bruto_suma['brt_suma'] - avans
    bruto_razlika = bruto_suma['brt_suma'] -  neto_suma['net_suma']


    context = {
        'korisnik': korisnik,
        'faktura': faktura,
        'prodaja': prodaja,
        'prodaja_5': prodaja[4:],
        'prodaja_24_40':prodaja[24:40],
        'prodaja_40_52':prodaja[40:52],
        'prodaja_8': prodaja_8,
        'prodaja_do_8': prodaja_do_8,
        'prodaja_do_16': prodaja_do_16,
        'prodaja_16': prodaja_16,
        'neto_suma': neto_suma,
        'bruto_suma': bruto_suma,
        'm': '1111',
        'prodaja_count': prodaja_count,
        'valuta':valuta,
        'avans': avans,
        'bruto_avans':bruto_suma_avans,
        'bruto_razlika': bruto_razlika
    }

    html_template = render_to_string('fakture/faktura_html.html', context)

    pdf_file = HTML(string=html_template,  base_url = request.build_absolute_uri()).write_pdf()
    response = HttpResponse(pdf_file, content_type='application/pdf')
    response['Content-Disposition'] = 'filename="faktura broj {}.pdf"'.format(faktura.broj_fakture)
    return response




@login_required
#@permission_required
def pocetna_stranica(request):
    context = {}

    if Faktura.objects.filter(broj_fakture__isnull=True):
        pass
    else:
        fakture = Faktura.objects.filter(broj_fakture__isnull=False).order_by('-broj_fakture')
        #datum = Faktura.objects.values(Year=TruncYear('datum_fakture')).distinct()
        datum = Faktura.objects.dates('datum_fakture', 'year')
        valute = Valute.objects.all().order_by('valute')
        zadnja_faktura_datum = Faktura.objects.all().order_by('-pk').first()
        predzadnja_faktura_datum = Faktura.objects.all().order_by('-pk')[1]
        zadnja = zadnja_faktura_datum.datum_fakture
        predzadnja = predzadnja_faktura_datum.datum_fakture
        context = {
            'fakture':fakture,
            'datum':datum,
            'valute': valute,
            'zadnja_faktura_datum': zadnja,
            'pd':predzadnja,

        }

    return render(request, 'bazni_template.html', context)

def base(request):
    return render(request, 'fakture/base_nativ.html', {})

class KreirajValute(LoginRequiredMixin, CreateView):
    model = Valute
    fields = '__all__'
    template_name = 'fakture/valute_create.html'
    success_url = reverse_lazy('fakture:kreiraj-valutu')

    def get_context_data(self, *args, **kwargs):
        context = super(KreirajValute, self).get_context_data(**kwargs)
        context['valute'] = Valute.objects.all().order_by('valute')
        return context

class ValuteUpdate(LoginRequiredMixin, UpdateView):
    model = Valute
    fields = ('bam_evro',)
    template_name = 'fakture/valuta_update.html'

    def get_success_url(self):
        return reverse_lazy('fakture:index')

class FaktureLista(LoginRequiredMixin, ListView):
    model = Faktura
    template_name = 'fakture/faktura_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(FaktureLista, self).get_context_data(**kwargs)
        context['datum'] = Faktura.objects.dates('datum_fakture', 'year')
        return context

@login_required
def faktura_po_godinama(request, year):
    fakture = Faktura.objects.filter(datum_fakture__year=year)

    return render(request, 'fakture/godina_fakture.html', {'fakture':fakture})

class KreirajFakturu(LoginRequiredMixin, CreateView):
    model = Faktura
    form_class = FakturaForma
    template_name = 'fakture/faktura_create.html'
    success_url = reverse_lazy('fakture:faktura-prodaja')

    def get_initial(self):
        if not Faktura.objects.filter(broj_fakture__isnull=False).exists():
            faktura = '0001'
            return {'broj_fakture': faktura}
        else:
            broj = Faktura.objects.filter(broj_fakture__isnull=False).order_by('-pk')[0]
            faktura1 = int(broj.broj_fakture)
            if faktura1 <= 9:
                faktura = '000'+ str(faktura1+1)
                return {'broj_fakture': faktura}
            elif 10 <= faktura1 <= 99:
                faktura = '00' + str(faktura1+1)
                return {'broj_fakture': faktura}
            elif 100 <= faktura1 <= 999:
                faktura = '0'+str(faktura1+1)
                return {'broj_fakture': faktura}
    def get_context_data(self, **kwargs):
        context = super(KreirajFakturu, self).get_context_data(**kwargs)
        context['valute'] = Valute.objects.all()
        context['kupci'] = Kupac.objects.all()
        return context

    def get_success_url(self):
        return reverse('fakture:faktura-prodaja', args={self.object.pk})



class KreirajFakturuProdaja(LoginRequiredMixin, CreateView):
    form_class = ProdajaForma
    template_name = 'fakture/faktura_create_nastavak.html'
    success_url = reverse_lazy('fakture:faktura-prodaja')
    def get_initial(self, **kwargs):
        if Faktura.objects.filter(broj_fakture__isnull=True):
            faktura = '0001'
        else:
            broj = Faktura.objects.get(id=self.kwargs['pk'])
            faktura = broj
        return {'faktura':faktura}

    def get_context_data(self, **kwargs):
        context = super(KreirajFakturuProdaja, self).get_context_data(**kwargs)
        faktura = Faktura.objects.get(id=self.kwargs['pk'])
        neto_suma = Prodaja.objects.filter(faktura_id=faktura.pk).aggregate(net_suma=Sum('neto_cijena'))
        bruto_suma = Prodaja.objects.filter(faktura__id=faktura.pk).aggregate(brt_suma=Sum('bruto_cijena'))

        context['faktura']= Faktura.objects.get(id=self.kwargs['pk'])
        context['prodaja'] = Prodaja.objects.all().filter(faktura__id=faktura.pk)
        context['neto_suma'] = neto_suma
        context['bruto_suma'] = bruto_suma
        context['pozicije'] = Pozicija.objects.all()
        context['usluge'] = Usluga.objects.all()
        return context
    def get_success_url(self):
        return reverse('fakture:faktura-prodaja', kwargs={'pk':self.object.faktura.pk})

class ProdajaDetalji(LoginRequiredMixin, DetailView):
    model = Prodaja
    template_name = 'fakture/prodaja_detail.html'
    def get_success_url(self):
        return reverse('fakture:faktura-prodaja', args={self.object.pk})

class ProdajaIzmjena(LoginRequiredMixin, UpdateView):
    model = Prodaja
    fields = '__all__'
    template_name = 'fakture/update_prodaja.html'
    def get_success_url(self):
        return reverse('fakture:faktura-prodaja', kwargs={'pk':self.object.faktura.pk})

class FakturaUpdate(LoginRequiredMixin, UpdateView):
    model = Faktura
    form_class = FakturaUpdateForm
    template_name = 'fakture/faktura_update.html'
    success_url = reverse_lazy('fakture:faktura-prodaja-izmjena')

    def get_success_url(self):
        return reverse('fakture:faktura-prodaja', args={self.object.pk})

class ProdajaGlavnaUpdate(LoginRequiredMixin, UpdateView):
    model = Prodaja
    form_class = ProdajaForma
    template_name = 'fakture/prodaja_glavna_update.html'
    success_url = reverse_lazy('fakture:faktura-prodaja-izmjena')


    def get_context_data(self, **kwargs):
        context = super(ProdajaGlavnaUpdate, self).get_context_data(**kwargs)
        faktura = Faktura.objects.get(id=self.kwargs['pk'])
        neto_suma = Prodaja.objects.filter(faktura__broj_fakture=faktura.broj_fakture).aggregate(
            net_suma=Sum('neto_cijena'))
        bruto_suma = Prodaja.objects.filter(faktura__broj_fakture=faktura.broj_fakture).aggregate(
            brt_suma=Sum('bruto_cijena'))

        context['faktura'] = Faktura.objects.get(id=self.kwargs['pk'])
        context['prodaja'] = Prodaja.objects.all().filter(faktura__broj_fakture=faktura.broj_fakture)
        context['neto_suma'] = neto_suma
        context['bruto_suma'] = bruto_suma
        return context

    def get_success_url(self):
        return reverse('fakture:faktura-prodaja-izmjena', kwargs={'pk': self.object.faktura.pk})



def faktura_skica_gotova(request, pk):
    faktura = Faktura.objects.get(id=pk)
    prodaja = Prodaja.objects.filter(faktura_id=pk)

nativ1/fakture/templates/fakture/faktura_list.html
{% extends 'fakture/base_nativ.html' %}
{% load static %}
{% block fakture %}
    {% if datum %}
    {% for d in datum %}
         <div class="fakture-lista-naslovna">
    <h2>Fakture za {{ d|date:'Y' }} godinu</h2>
    <ul>
    {% for faktura in faktura_list %}
          {% if d|date:'Y' == faktura.datum_fakture|date:'Y' %}
        <li><a href="{% url 'fakture:faktura-skica' faktura.pk %}">Broj fakture {{ faktura.broj_fakture }}</a>;  {{ faktura.kupac }} -- Datum fakture {{ faktura.datum_fakture|date:'d-m-Y' }} </li>
        {% endif %}
    {% endfor %}
    </ul>
         </div>
    {% endfor %}
{% else %}
<h3>U bazi trenutno nema kreiranih faktura!</h3>
{% endif %}
{% endblock %}
{% block fakture_godine %}
    {% if datum %}
        <div class="fakture-godine">
        <h2>Fakture po godinama</h2>
        {% for d in datum %}
        <p><a href="{% url 'fakture:fakture_po_godinama' d|date:'Y' %}">Fakture za {{ d|date:'Y' }} godinu</a></p>
        {% endfor %}
    </div>
    {% else %}
{% endif %}
{% endblock %}
{% block faktura_button %}
    <div>
    <p>Kreiraj novu fakturu: </p>
    <form>
        <button formaction="{% url 'fakture:kreiraj-fakturu' %}">Kreiraj</button>
    </form>
    </div>
{% endblock %}

nativ1/fakture/templates/fakture/kupac_izmjeni.html
{% extends 'fakture/base_nativ.html' %}
{% block fakture %}
    <form method="post" action="">
{% csrf_token %}
    <table>
{{ form.as_table }}
        </table>
<input type="submit" value="Spasi promjene">
        </form>
    <br>
        <form>
        <button formaction="{% url 'fakture:lista-kupci' %}">Vrati se bez promjena</button>
            </form>
{% endblock %}

nativ1/fakture/templates/fakture/kupac_list.html
{% extends 'fakture/base_nativ.html' %}
{% block fakture %}
    {% if kupac_list %}
    {% for z in zemlja %}
        <div class="fakture-lista-naslovna">
        <h2>Država {{ z.drzava }}</h2>
        <ul>
            {% for k in kupac_list %}
        {% if k.drzava == z.drzava %}
            <li>Ime i prezime kupca: {{ k.ime }} {{ k.prezime }}, Naziv preduzeća: {{ k.naziv_firme }}, Drzava: {{ k.drzava }}, <a href="{% url 'fakture:kupac-detalji' k.pk %}">Izmjeni podatke</a></li>
                {% endif %}
                {% endfor %}
                </ul>
        </div>


    {% endfor %}
        {% else %}
        <h2>Trenutno u bazi nema unešenih kupaca!</h2>
    {% endif %}

{% endblock %}
    {% block faktura_button %}
    <div>
    <p>Kreiraj novog kupca: </p>
    <form>
        <button formaction="{% url 'fakture:kupac-novi' %}">Kreiraj</button>
    </form>
    </div>
{% endblock %}

nativ1/fakture/templates/fakture/ponuda_godine.html
{% extends 'fakture/base_nativ.html' %}
{% block fakture %}

    <div class="fakture-lista-naslovna">
        <h2>Ponuda za {{ ponuda.model.datum_ponude|date:'Y' }} godinu</h2>
            <ul>
                 {% for p in ponuda  %}
                <li><a href="{% url 'fakture:ponuda-skica' p.pk %}">Broj ponude {{ p.broj_ponude }}</a>;  {{ p.kupac }} -- Datum ponude {{ p.datum_ponude|date:'d-m-Y' }}</li>
                {% endfor %}
            </ul>
    </div>
{% endblock %}
{% block faktura_button %}
    <div>
    <p>Kreiraj novu ponudu: </p>
    <form>
        <button formaction="{% url 'fakture:ponuda-create' %}">Kreiraj</button>
    </form>
    </div>
{% endblock %}

nativ1/fakture/templates/fakture/ponuda_prodaja_detail.html
{% extends 'fakture/base_nativ.html' %}
{% block fakture %}

    <h2>Podaci unešeni u ponudu broj {{ prodajaponuda.ponuda.broj_ponude }}</h2>
    <p>Kupac: {{ prodajaponuda.ponuda.kupac.naziv_firme }}</p>
    <p>Broj ponude: {{ prodajaponuda.ponuda.broj_ponude }}</p>
    <p>Usluga: {{ prodajaponuda.opis_usluge }}</p>
    <p>Pozicija: {{ prodajaponuda.pozicija.naziv_pozicije }} -- Kod: {{ prodajaponuda.pozicija.pos_NSN }}{{ prodajaponuda.pozicija.pos_broj }}</p>
    <p>Neto cijena proizvoda: {{ prodajaponuda.neto_cijena_proizvoda }}</p>
    <p>PDV: {{ prodajaponuda.pdv }} %</p>
    <p>Bruto cijena proizvoda: {{ prodajaponuda.bruto_cijena_proizvoda }}</p>
    <p>Neto cijena: {{ prodajaponuda.neto_cijena }}</p>
    <p>Bruto cijena: {{ prodajaponuda.bruto_cijena }}</p>
    <form action="{% url 'fakture:ponuda-prodaja-izmjena' prodajaponuda.pk %}">
    {% csrf_token %}
    <input type="submit" value="Izmjeni">
    </form>
    <br>
            <form>
        <button formaction="{% url 'fakture:ponuda-prodaja-brisanje' prodajaponuda.pk%}">Izbriši unos?</button>
            </form>
    <br>
        <form>
        <button formaction="{% url 'fakture:ponuda-prodaja' prodajaponuda.ponuda.pk%}">Vrati se bez promjena</button>
            </form>
{% endblock %}

nativ1/fakture/templates/fakture/usluge_list.html
{% extends 'fakture/base_nativ.html' %}
{% load static %}
{% block style %}
    <style>
.pozicije{
position: absolute;
top: 100px;
left: 850px;
width: 400px;
}
.glavna-tabela-tabela th, td{
  text-align: center;
  margin: 0;
  padding: 0;
  border-collapse: collapse;
    border: darkblue solid 1px;
    color: darkblue;
}
.glavna-tabela-tabela {
    border-collapse: collapse;
}
</style>
{% endblock %}
{% block fakture %}
    {% if usluga_list %}

         <div class="fakture-lista-naslovna" style="width: 500px">
    <h2>Usluge</h2>
    <ul>
    {% for u in usluga_list %}
        <li>Usluga: {{ u.opis_usluge }} -- <a href="{% url 'fakture:usluge-update' u.pk %}">Izmjeni elemente usluge?</a></li>
        <hr>

    {% endfor %}
    </ul>
         </div>

{% else %}
<h2>U bazi trenutno nema kreiranih usluga!</h2>
{% endif %}
{% endblock %}

{% block faktura_button %}
    <div>
    <p>Kreiraj novu uslugu: </p>
    <form>
        <button formaction="{% url 'fakture:usluge-kreiraj' %}">Kreiraj</button>
    </form>
    <br>
    <br>
      <p>Kreiraj novu poziciju: </p>
    <form>
        <button formaction="{% url 'fakture:pozicije-kreiraj' %}">Kreiraj</button>
    </form>
    </div>
{% endblock %}
{% block pozicije %}
    <div class = fakture-lista-naslovna>
    <h2 >Pregled unešenih pozicija</h2>
    <table style="width: 100%; border: darkblue solid 1px" class="glavna-tabela-tabela">
    <tr>
        <th>Naziv pozicije</th>
        <th>Pos NSN</th>
        <th>Cijena</th>
        <th>Jedinica<br>mjere</th>
        <th>Izmjeni podatke</th>
    </tr>
    {% for p in pozicije %}
        <tr>
        <td>{{ p.naziv_pozicije }}</td>
        <td>{{ p.pos_NSN }}{{ p.pos_broj }}</td>
        <td>{{ p.cijena }}</td>
        <td>{{ p.jedinica_mjere }}</td>
        <td><a href="{% url 'fakture:pozicija-update' p.pk %}">Izmjeni?</a></td>
    </tr>
    {% endfor %}
    </table>
    </div>
{% endblock %}

nativ1/fakture/templates/fakture/valute_create.html
{% extends 'fakture/base_nativ.html' %}
{% block fakture %}
    <h2>Unesite elemente u tabelu Valute.</h2>
    <form action="{% url 'fakture:kreiraj-valutu' %}" method="post">
    {% csrf_token %}
        <table>
    {{ form.as_table }}
            </table>
    <input type="submit" value="Spasi valutu">
    </form>
    <br>
    <form>
    <button formaction="{% url 'fakture:index' %}">Vrati na početnu</button>
    </form>

{% endblock %}
{% block valute %}
    {% if valute %}
    <h2>Trenutna vrijednost valuta u odnosu na BAM</h2>
    <ul>
    {% for v in valute %}
        <li>Vrijednost valute {{ v.valute }}: {{ v.vrijednost_valute }}<a href="{% url 'fakture:valute_update' v.pk %}">                Promjeni kurs?</a></li>
    {% endfor %}
    </ul>
    {% endif %}
{% endblock %}